set showmatch

set encoding=utf-8
set textwidth=160
set colorcolumn=+1
set number
set numberwidth=5
set wrap
set autoread
set relativenumber
"set cursorcolumn
"set cursorline
set noshowmode
execute pathogen#infect()
set background=dark
set termguicolors
set ignorecase
syntax on
filetype plugin indent on
colorscheme gruvbox
autocmd ColorScheme * highlight CocErrorFloat guifg=#ffffff
autocmd ColorScheme * highlight CocInfoFloat guifg=#ffffff
autocmd ColorScheme * highlight CocWarningFloat guifg=#ffffff
autocmd ColorScheme * highlight SignColumn guibg=#adadad
"Automate process to download xclip
map <C-y> :w !xclip -sel c <CR><CR>
map <C-a> <ESC>^
imap <C-a> <ESC>I
map <C-e> <ESC>$
imap <C-e> <ESC>A
inoremap <M-f> <ESC><Space>Wi
inoremap <M-b> <Esc>Bi
inoremap <M-d> <ESC>cW

" Normal mode
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==

" Insert mode
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi

" Visual mode 
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
vnoremap y y$

nnoremap <C-n> :NERDTreeToggle<CR>

nnoremap gev :e $MYVIMRC<CR>
nnoremap gsv :so $MYVIMRC<CR>

nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p

inoremap <C-s> <esc>:w<cr>
nnoremap <C-s> :w<cr>

set rtp+=~/.fzf
let mapleader = "f"
nnoremap <silent> <leader>f :FZF<CR>
